### ISSUE TITLE
Test protocol in MATLAB GUI emulator mode

### ISSUE THREAD

**Issue by ckarageorgkaneen** [HenryJFlynn/mouse2afc#2]

**Comment by HenryJFlynn** [comment]
^ Me messing around

**Comment by HenryJFlynn** [comment]
Will be retroactively added my thoughts which were in a private doc into this comment section. I am trying to do this whole organizational thing correctly.

**Comment by HenryJFlynn** [comment]
First step is to follow ioanna’s instructions on how to set up a pc from scratch

**Comment by HenryJFlynn** [comment]
She instructions to install psychtookbox are for windows, since i am using linus i must do this part myself.

**Comment by HenryJFlynn** [comment]
FOllowed the instructions on their website, 
http://psychtoolbox.org/download#Linux 
http://neuro.debian.net/install_pkg.html?p=matlab-psychtoolbox-3

**Comment by HenryJFlynn** [comment]
Downloading python packages

  WARNING: The scripts f2py, f2py3 and f2py3.10 are installed in '/home/henry/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts fonttools, pyftmerge, pyftsubset and ttx are installed in '/home/henry/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

**Comment by HenryJFlynn** [comment]
Got matlab installed and i can run sanworks examples

**Comment by HenryJFlynn** [comment]
Mouse2afc gives me this error

Unrecognized function or variable 'DataPath'.

Error in Mouse2AFC (line 22)
dataPath = DataPath(BpodSystem);

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Error in NewLaunchManager>LaunchProtocol (line 732)
run(ProtocolPath);
 
Error while evaluating DestroyedObject Callback.

**Comment by HenryJFlynn** [comment]
I skipped a step in ioanna instructions which causes that error.

**Comment by HenryJFlynn** [comment]
Now i hit this


![Image](https://github.com/HenryJFlynn/mouse2afc/assets/130571023/35bafc57-06a9-494c-a11f-f854b3f7955f)

**Comment by HenryJFlynn** [comment]
Gonna change line 63 
createMMFile('/Documents/Bpod/C:\BpodUser/', 'mmap_matlab_randomdot.dat', file_size);
/Documents/Bpod/C:\BpodUser

           createMMFile('/Documents/Bpod/C:\BpodUser/', 'mmap_matlab_randomdot.dat', file_size);

**Comment by HenryJFlynn** [comment]
I should back up. Before that happens I get this pop up


![Image](https://github.com/HenryJFlynn/mouse2afc/assets/130571023/624c1962-d3ce-46ff-8113-fcc4dabbbf38)

**Comment by HenryJFlynn** [comment]
I think this is the problematic line: Line 116 of BpodObject.m 

           obj.Path.LocalDir = 'C:\BpodUser'; %fullfile(obj.Path.ParentDir, 'BpodUser');

**Comment by HenryJFlynn** [comment]
I deleted the stuff in purple and uncommented the rest of the line. I believed that fixed it

**Comment by ckarageorgkaneen** [comment]
> Now i get this error Unrecognized field name "DotsPulseCoherence".
> 
> Error in GenNextTrial (line 137) if ~isnan(NextTrial.DotsPulseCoherence) && NextTrial.DotsPulseCoherence
> 
> Error in Mouse2AFC (line 81) BpodSystem.Data.Timer(1)] = GenNextTrial(BpodSystem.Data.Custom.Trials(1),...
> 
> Error in run (line 91) evalin('caller', strcat(script, ';'));
> 
> Error in NewLaunchManager>LaunchProtocol (line 732) run(ProtocolPath);
> 
> Error while evaluating DestroyedObject Callback.

Format code such as the above like this, for readability:

```matlab
Unrecognized field name "DotsPulseCoherence".

Error in GenNextTrial (line 137)
if ~isnan(NextTrial.DotsPulseCoherence) && NextTrial.DotsPulseCoherence

Error in Mouse2AFC (line 81)
BpodSystem.Data.Timer(1)] = GenNextTrial(BpodSystem.Data.Custom.Trials(1),...

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Error in NewLaunchManager>LaunchProtocol (line 732)
run(ProtocolPath);

Error while evaluating DestroyedObject Callback.
```

**Comment by HenryJFlynn** [comment]
To fix this go open EndBpod.m. In console enter `BpodSystem.Status.BeingUsed = 0`. Run EndBpod.m

**Comment by HenryJFlynn** [comment]
The previous error: 
```
Unrecognized field name "DotsPulseCoherence".

Error in GenNextTrial (line 137)
if ~isnan(NextTrial.DotsPulseCoherence) && NextTrial.DotsPulseCoherence

Error in Mouse2AFC (line 81)
 BpodSystem.Data.Timer(1)] = GenNextTrial(BpodSystem.Data.Custom.Trials(1),...

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Error in NewLaunchManager>LaunchProtocol (line 732)
run(ProtocolPath);
 
Error while evaluating DestroyedObject Callback.
```

is caused by an outdated version of the protocol as well as some additional files which ioanna didn't initially send

**Comment by HenryJFlynn** [comment]
With the updated files and additions to the matlab path, the protocol runs smoothly in emulator mode

**Comment by ckarageorgkaneen** [comment]
> With the updated files and additions to the matlab path, the protocol runs smoothly in emulator mode

Great!

> Will need to update ioanna's instructions doc as well as the repo to reflect the changes for future use

What doc? Where is it? Link?

**Comment by HenryJFlynn** [comment]
Here is the google drive link to the ioanna's setup instructions i referenced: https://docs.google.com/document/d/1IQuRvGm5R12NKdysfzQM0zcSOXOglUvaVOv-eGqve7k/edit?usp=sharing

In the future, this doc will be in the repo or something like that for easy access

**Comment by ckarageorgkaneen** [comment]
> Here is the google drive link to the ioanna's setup instructions i referenced: https://docs.google.com/document/d/1IQuRvGm5R12NKdysfzQM0zcSOXOglUvaVOv-eGqve7k/edit?usp=sharing
> 
> In the future, this doc will be in the repo or something like that for easy access

@HenryJFlynn Paste these instructions in #5.
