### ISSUE TITLE
Run existing protocol on pybpod-api

### ISSUE THREAD

**Issue by HenryJFlynn** [HenryJFlynn/mouse2afc#4]

**Comment by HenryJFlynn** [comment]
first must set up a venv in the using the pybpod-api requirements.txt file

**Comment by HenryJFlynn** [comment]
trying to run `emulator_run_manual_override.py,` get this error:

ModuleNotFoundError: No module named 'AnyQt'

**Comment by HenryJFlynn** [comment]
May be something to do with my library setup

**Comment by HenryJFlynn** [comment]
Error was caused by me doing a `pip install pybpod-api` and not doing a `pip install -e` the pybpid-api library. The `-e` downloads the library specified in the setup file `setup.py` which in this case is different than the one on the interent. Additionally, another possible problem was that the library was installed outside of my venv. To solve this, everything in the venv was uninstalled, as well the pybpod libraries which were downloaded outside the venv. 

Whatever I did, the libraries were not where they were suppose to be

Steps for this not to happened again. 
1. Create venv `conda create -n venv_name`
           - Can use `conde env list` to verify it was made
           - can also specify python version in this step w the add-on of `python = ...`
2. activate the env
3. cd into the pybpod-api folder
4. `pip install -e.` and `pip install -r requirements`

I think that is all

**Comment by HenryJFlynn** [comment]
regarding the previous error about Any Qt and pyQt5, create a new mouse2afc env with these3 changes. the mouse2afc env is pybpod clone + pyqt5

**Comment by HenryJFlynn** [comment]
I can run the emulator examples no problem. Moving to try and run mouse2afc, i get this error: 

```
stderr;2023-05-17 12:55:19.168568;;ValueError;;
stderr;2023-05-17 12:55:19.168596;;: ;;
stderr;2023-05-17 12:55:19.168621;;'Valve8' is not in list;;
```

May have to do with settings and the firmware. What version has 8 valves?

**Comment by HenryJFlynn** [comment]
added `user_settings.py` from pybpod-api into mouse2afc. it did nothing

**Comment by HenryJFlynn** [comment]
Also getting this error:

`Import "pybpodapi.protocol" could not be resolved`





![Image](https://github.com/HenryJFlynn/mouse2afc/assets/130571023/2b558e42-85c3-4758-b2fa-83efba5fc5ec)




the library name ( when i do pip list) is pybpod-api, while the import is pybpodapi. Dash vs no dash. This may be causing the squiggly and error

**Comment by HenryJFlynn** [comment]
^ in ipython i can import pybpodapi, i can import pybpod.protocol and i type out line 2 and it is fine

**Comment by HenryJFlynn** [comment]
may have a lead  with `constants.py`

**Comment by HenryJFlynn** [comment]
This is the full error code i am trying to solve printed from the vscode debugger
```
Exception has occurred: ValueError
'Valve8' is not in list
  File "/home/henry/Documents/pybpod-api/pybpodapi/state_machine/state_machine_base.py", line 203, in add_state
    OutputChannel.Valve + str(action_value)
  File "/home/henry/Documents/mouse2afc/state_matrix.py", line 421, in __init__
    output_actions=(CloseChamber + AirFlowStimDelayOff))
  File "/home/henry/Documents/mouse2afc/mouse2afc.py", line 99, in run
    self._bpod, self._task_parameters, self._data, i_trial)
  File "/home/henry/Documents/mouse2afc/emulator_run_manual_override", line 11, in main
    Mouse2AFC(bpod).run()
  File "/home/henry/Documents/mouse2afc/emulator_run_manual_override", line 15, in <module>
    main()
ValueError: 'Valve8' is not in list
```

`state_machine_base.py` is causing the problem when it tried to add the state `WaitForStimulus`.

**Comment by HenryJFlynn** [comment]
![Image](https://github.com/HenryJFlynn/mouse2afc/assets/130571023/35f1c4c1-ce8c-49ae-b1a8-0581d5b76e
something seems of with `behavior_port_names` and `behavior_port_indexes

**Comment by HenryJFlynn** [comment]
![Image](https://github.com/HenryJFlynn/mouse2afc/assets/130571023/acaf2c91-3080-47ee-9b17-042db8a185e9)

`output_channel_names` has only ports 1-4

**Comment by HenryJFlynn** [comment]
in `state_Matrix.py` CenterPWM = 13, tho in matlab it is =0


![Image](https://github.com/HenryJFlynn/mouse2afc/assets/130571023/70d620e5-61a3-4480-b21f-2b7b1cc14b78)



![Image](https://github.com/HenryJFlynn/mouse2afc/assets/130571023/796fba84-b3da-49f6-b57f-7501fcf5e46e)

**Comment by HenryJFlynn** [comment]
```
self.add_state(state_name=str(MatrixState.TriggerWaitForStimulus),
                       state_timer=WireTTLDuration,
                       state_change_conditions={
            CenterPortOut: str(MatrixState.StimDelayGrace),
            Bpod.Events.Tup: str(MatrixState.WaitForStimulus)},
            output_actions=(CloseChamber + AirFlowStimDelayOff))
```
`output_actions=(CloseChamber + AirFlowStimDelayOff)) = [('Valve', 8)]`

**Comment by HenryJFlynn** [comment]
Found the reason for  `Valve8' is not in list`



![Image](https://github.com/HenryJFlynn/mouse2afc/assets/130571023/29f6788d-5f4c-4dc4-87ff-0e8a68ccb37c)

Those two boxes should not be checked

**Comment by ckarageorgkaneen** [comment]
Errors such as the above are resolved by setting the machine type to `1` (r0.5) and lowering the firmware version.

**Comment by ckarageorgkaneen** [comment]
> Conf gets its settings from the user_settings.py file which should be in the same folder as the protocol.
> 
> One can specify the machine type and firmware type in user settings
> 
> For machine type==1, there are more wire ports required. See sanworks documentation for each machine type and the types of inputs and outputs it had.
> 
> Machine type==3 has no wired ports yet the protocol calls for a wired port, therefore there must be a problem with the settings.
> 
> Note to self: I wrote this quickly, check back to see if this explanation is accurate

Great, thanks for the follow-up.

**Comment by HenryJFlynn** [comment]
It is possible that the previous error, 'Valve8' thing, was also due to this machine type error

**Comment by HenryJFlynn** [comment]
I should commit user_settings

Only the addition of the firmware and machine type

Not the session path

Possibly add a note about the session path

I wonder if the README has directions

**Comment by HenryJFlynn** [comment]
``` python
stderr;2023-05-18 10:41:16.426886;;|  File "/home/henry/Documents/mouse2afc/emulator_run", line 12, in <module>
|;;
stderr;2023-05-18 10:41:16.427022;;    ;;
stderr;2023-05-18 10:41:16.427059;;main();;
stderr;2023-05-18 10:41:16.427085;;|
|;;
stderr;2023-05-18 10:41:16.427113;;|  File "/home/henry/Documents/mouse2afc/emulator_run", line 8, in main
|;;
stderr;2023-05-18 10:41:16.427191;;    ;;
stderr;2023-05-18 10:41:16.427221;;Mouse2AFC(bpod).run();;
stderr;2023-05-18 10:41:16.427247;;|
|;;
stderr;2023-05-18 10:41:16.427275;;|  File "/home/henry/Documents/mouse2afc/mouse2afc.py", line 103, in run
|;;
stderr;2023-05-18 10:41:16.427389;;    ;;
stderr;2023-05-18 10:41:16.427420;;if not self._bpod.run_state_machine(sma):;;
stderr;2023-05-18 10:41:16.427446;;|
|;;
stderr;2023-05-18 10:41:16.427474;;|  File "/home/henry/Documents/pybpod-api/pybpodapi/bpod/bpod_base.py", line 331, in run_state_machine
|;;
stderr;2023-05-18 10:41:16.427608;;    ;;
stderr;2023-05-18 10:41:16.427640;;sma, opcode, data, state_change_indexes):;;
stderr;2023-05-18 10:41:16.427667;;|
|;;
stderr;2023-05-18 10:41:16.427695;;|  File "/home/henry/Documents/pybpod-api/pybpodapi/bpod/bpod_base.py", line 627, in __process_opcode
|;;
stderr;2023-05-18 10:41:16.427878;;    ;;
stderr;2023-05-18 10:41:16.427912;;self._emulator.mirror_state(sma.current_state);;
stderr;2023-05-18 10:41:16.427941;;|
|;;
stderr;2023-05-18 10:41:16.427969;;|  File "/home/henry/Documents/pybpod-api/pybpodapi/bpod/emulator/emulator.py", line 443, in mirror_state
|;;
stderr;2023-05-18 10:41:16.428125;;    ;;
stderr;2023-05-18 10:41:16.428158;;new_output_channel, new_output_value);;
stderr;2023-05-18 10:41:16.428184;;|
|;;
stderr;2023-05-18 10:41:16.428211;;|  File "/home/henry/Documents/pybpod-api/pybpodapi/bpod/emulator/emulator.py", line 230, in _send_output_to_gui_server
|;;
stderr;2023-05-18 10:41:16.428315;;    ;;
stderr;2023-05-18 10:41:16.428345;;self.socket.connectToServer(;;
stderr;2023-05-18 10:41:16.428370;;|
|;;
stderr;2023-05-18 10:41:16.428397;;|  File "/home/henry/Documents/pybpod-api/pybpodapi/bpod/emulator/emulator.py", line 84, in socket
|;;
stderr;2023-05-18 10:41:16.428481;;    ;;
stderr;2023-05-18 10:41:16.428510;;self._socket = QtNetwork.QLocalSocket();;
stderr;2023-05-18 10:41:16.428536;;|
|;;
stderr;2023-05-18 10:41:16.428568;;NameError;;
stderr;2023-05-18 10:41:16.428595;;: ;;
stderr;2023-05-18 10:41:16.428621;;name 'QtNetwork' is not defined;;
stderr;2023-05-18 10:41:16.428647;;|
|;;
```

**Comment by ckarageorgkaneen** [comment]
> ...
> |;;
> stderr;2023-05-18 10:41:16.428568;;NameError;;
> stderr;2023-05-18 10:41:16.428595;;: ;;
> stderr;2023-05-18 10:41:16.428621;;name 'QtNetwork' is not defined;;
> stderr;2023-05-18 10:41:16.428647;;|
> |;;

What you can do to fix this is, in `emulator.py`:
1. Remove the `try:` line and the import lines inside the try block, as well as the except code block
2. Write the following at the top of the `emulator.py` module:
```python
try:
    # imports ...
except ImportError:
   GUI_ENABLED = False
```
3. Add a `gui_enabled` attribute to the emulator constructor and assign it the constant `GUI_ENABLED`
4. Go to the `mirror_state` function and do this:
```python
if self.gui_enabled:
    self._send_output_to_gui_server(...)
```

Doing so will facilitate sending output to the gui server **only** when we are actually working with the GUI (meaning, we have installed the `AnyQt` library).

**Comment by ckarageorgkaneen** [comment]
https://github.com/HenryJFlynn/pybpod-api/issues/1 is still blocking the successful running of this protocol. So, let's close this issue when that is merged also!

**Comment by ckarageorgkaneen** [comment]
I re-set this issue's status to `In Progress`. In general, an issue's status is automatically (or should be manually) st to `Done` only after it's closed. And an issue should be closed only after any pending PRs have been merged.

**Comment by HenryJFlynn** [comment]
> [HenryJFlynn/pybpod-api#1](https://github.com/HenryJFlynn/pybpod-api/issues/1) is still blocking the successful running of this protocol. So, let's close this issue when that one is merged also!

The PR has been closed and changes have been merged. Everything works as intended
