### ISSUE TITLE
Document Bpod workspace environment instructions

### ISSUE THREAD

**Issue by ckarageorgkaneen** [HenryJFlynn/mouse2afc#5]
https://docs.google.com/document/d/1IQuRvGm5R12NKdysfzQM0zcSOXOglUvaVOv-eGqve7k/edit?usp=sharing

**Comment by HenryJFlynn** [comment]
Think I will add these details to the README in the repo: https://github.com/HenryJFlynn/Mouse2AFC-matlab

**Comment by HenryJFlynn** [comment]
This repo: https://github.com/HenryJFlynn/Mouse2AFC-matlab contains a `README.md` with a revised version of the install instructions in the above comment. 

I have created a pull request to https://github.com/ioannapandi/Mouse2AFC to merge forks. 

I think my work is done.
